import './global.css';
import Header from './components/Header';




export const metadata = {
  title: 'Welcome to coinroutes-test',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className='container mx-auto'>
          {children}
        </div>
      </body>
    </html>
  );
}
